use tree_sitter::{Language, Node};

use super::Grammar;
use crate::highlight::{c_members, cmake_outline, imports, includes, site, types};

const HIGHLIGHTS: &str = include_str!("../../../queries/cmake/highlights.scm");

pub const KEYWORDS: &[&str] = &[
    "AND",
    "BOOL",
    "CACHE",
    "CMAKE_BINARY_DIR",
    "CMAKE_BUILD_TYPE",
    "CMAKE_CURRENT_BINARY_DIR",
    "CMAKE_CURRENT_LIST_DIR",
    "CMAKE_CURRENT_SOURCE_DIR",
    "CMAKE_CXX_COMPILER",
    "CMAKE_CXX_FLAGS",
    "CMAKE_CXX_STANDARD",
    "CMAKE_CXX_STANDARD_REQUIRED",
    "CMAKE_C_COMPILER",
    "CMAKE_C_FLAGS",
    "CMAKE_C_STANDARD",
    "CMAKE_EXPORT_COMPILE_COMMANDS",
    "CMAKE_INSTALL_PREFIX",
    "CMAKE_MODULE_PATH",
    "CMAKE_SOURCE_DIR",
    "COMMAND",
    "DEFINED",
    "DEPENDS",
    "EXISTS",
    "FALSE",
    "FATAL_ERROR",
    "FILEPATH",
    "FORCE",
    "GLOB",
    "GLOB_RECURSE",
    "IN_LIST",
    "INTERFACE",
    "INTERNAL",
    "MATCHES",
    "MODULE",
    "NOT",
    "OFF",
    "ON",
    "OR",
    "PARENT_SCOPE",
    "PATH",
    "PRIVATE",
    "PROJECT_BINARY_DIR",
    "PROJECT_NAME",
    "PROJECT_SOURCE_DIR",
    "PUBLIC",
    "QUIET",
    "REQUIRED",
    "SHARED",
    "STATIC",
    "STATUS",
    "STREQUAL",
    "STRING",
    "TARGET",
    "TRUE",
    "VERSION",
    "VERSION_GREATER_EQUAL",
    "VERSION_LESS",
    "WARNING",
    "add_compile_definitions",
    "add_compile_options",
    "add_custom_command",
    "add_custom_target",
    "add_definitions",
    "add_dependencies",
    "add_executable",
    "add_library",
    "add_link_options",
    "add_subdirectory",
    "add_test",
    "block",
    "break",
    "cmake_minimum_required",
    "cmake_parse_arguments",
    "cmake_path",
    "cmake_policy",
    "configure_file",
    "continue",
    "else",
    "elseif",
    "enable_language",
    "enable_testing",
    "endblock",
    "endforeach",
    "endfunction",
    "endif",
    "endmacro",
    "endwhile",
    "execute_process",
    "export",
    "FetchContent_Declare",
    "FetchContent_MakeAvailable",
    "file",
    "find_file",
    "find_library",
    "find_package",
    "find_path",
    "find_program",
    "foreach",
    "function",
    "get_filename_component",
    "get_property",
    "get_target_property",
    "if",
    "include",
    "include_directories",
    "include_guard",
    "install",
    "link_directories",
    "link_libraries",
    "list",
    "macro",
    "mark_as_advanced",
    "math",
    "message",
    "option",
    "project",
    "return",
    "separate_arguments",
    "set",
    "set_property",
    "set_target_properties",
    "source_group",
    "string",
    "target_compile_definitions",
    "target_compile_features",
    "target_compile_options",
    "target_include_directories",
    "target_link_directories",
    "target_link_libraries",
    "target_link_options",
    "target_precompile_headers",
    "target_sources",
    "try_compile",
    "unset",
    "while",
];

pub fn grammar() -> Grammar {
    Grammar {
        language: Language::new(tree_sitter_cmake::LANGUAGE),
        highlights: HIGHLIGHTS,
        keywords: KEYWORDS,
        local_kinds: &["variable"],
        declares: crate::highlight::locals::no_declares,
        symbol_kinds: &["variable", "identifier", "unquoted_argument"],
        qualifier: no_qualifier,
        outline: cmake_outline::outline,
        member_ops: &[],
        member_kinds: &[],
        receiver_type: c_members::no_receiver,
        type_table: types::empty_table,
        includes: includes::no_includes,
        site: site::plain_site,
        imports: imports::no_imports,
    }
}

fn no_qualifier(_: Node<'_>, _: &str) -> Option<String> {
    None
}
