use tree_sitter::{Language, Node};

use super::Grammar;
use crate::highlight::editing::{EditingKinds, make_folds};
use crate::highlight::{context, imports, includes, make_outline, members, site, types};

const HIGHLIGHTS: &str = include_str!("../../../queries/make/highlights.scm");

pub const KEYWORDS: &[&str] = &[
    ".DEFAULT_GOAL",
    ".DELETE_ON_ERROR",
    ".EXPORT_ALL_VARIABLES",
    ".NOTPARALLEL",
    ".ONESHELL",
    ".PHONY",
    ".PRECIOUS",
    ".SECONDARY",
    ".SILENT",
    ".SUFFIXES",
    "AR",
    "ARFLAGS",
    "AS",
    "CC",
    "CFLAGS",
    "CPPFLAGS",
    "CURDIR",
    "CXX",
    "CXXFLAGS",
    "LDFLAGS",
    "LDLIBS",
    "MAKE",
    "MAKECMDGOALS",
    "MAKEFLAGS",
    "MAKEFILE_LIST",
    "RM",
    "SHELL",
    "VPATH",
    "abspath",
    "addprefix",
    "addsuffix",
    "and",
    "basename",
    "call",
    "define",
    "dir",
    "else",
    "endef",
    "endif",
    "error",
    "eval",
    "export",
    "file",
    "filter",
    "filter-out",
    "findstring",
    "firstword",
    "foreach",
    "if",
    "ifdef",
    "ifeq",
    "ifndef",
    "ifneq",
    "include",
    "info",
    "join",
    "lastword",
    "notdir",
    "or",
    "override",
    "patsubst",
    "private",
    "realpath",
    "shell",
    "sinclude",
    "sort",
    "strip",
    "subst",
    "suffix",
    "undefine",
    "unexport",
    "value",
    "vpath",
    "warning",
    "wildcard",
    "word",
    "wordlist",
    "words",
];

pub fn grammar() -> Grammar {
    Grammar {
        language: Language::new(tree_sitter_make::LANGUAGE),
        highlights: HIGHLIGHTS,
        keywords: KEYWORDS,
        local_kinds: &[],
        declares: crate::highlight::locals::no_declares,
        local_detail: crate::highlight::locals::no_detail,
        symbol_kinds: &["word"],
        qualifier: no_qualifier,
        outline: make_outline::outline,
        member_ops: &[],
        member_kinds: &[],
        receiver: members::no_receiver,
        type_table: types::empty_table,
        includes: includes::no_includes,
        site: site::plain_site,
        context: context::make_context,
        imports: imports::no_imports,
        editing: EditingKinds {
            strings: &[],
            comments: &["comment"],
            bodies: &[],
            folds: make_folds,
        },
    }
}

fn no_qualifier(_: Node<'_>, _: &str) -> Option<String> {
    None
}
