mod attrs;
mod cargo_toml;
mod crate_extract;
mod crate_names;
mod crate_walk;
mod docs;
mod emit;
mod error;
mod external;
mod glob;
mod impls;
mod item;
mod mod_walk;
mod mods;
mod path_index;
mod reach;
mod reexport;
mod scan;
mod source;
mod ts;
mod types_walk;
mod use_walk;
mod variants;
mod version;
mod vis;
mod walk;

pub use cargo_toml::{parse_toml, workspace_members};
pub use crate_extract::{CrateExtract, CrateItems, plain as plain_extract};
pub use crate_names::normalized;
pub use crate_walk::{extract_crate, extract_crate_parts, extract_crate_with_version};
pub use error::ExtractError;
pub use external::External;
pub use item::{CrateContext, ItemDoc, Scope, Visibility};
pub use scan::read_rs;
pub use source::{extract_parsed, extract_source};
pub use version::EXTRACTOR_VERSION;
