import Foundation

extension SelfTestCoverage {
    static let fileEditClaims: [String: [String]] = [
        "Ride › About Ride": ["menu about", "menu about close"],
        "Ride › Settings…": ["menu settings", "menu settings close"],
        "Ride › Hide Ride": ["menu hide", "menu unhide"],
        "Ride › Quit Ride": ["menu quit cancel"],
        "Help › Keyboard Shortcuts": ["menu shortcuts", "menu shortcuts close"],
        "File › New Project…": ["menu new project", "menu new project cancel"],
        "File › New File…": ["menu new file"],
        "File › New Buffer": ["menu new buffer"],
        "File › New Folder…": ["menu new folder", "menu new folder exists"],
        "File › Open…": ["menu open"],
        "File › Open Recent › demo": ["menu open recent", "menu open recent pruned"],
        "File › Close Workspace": ["menu close workspace"],
        "File › Save": ["menu save"],
        "File › Save As…": ["menu save as"],
        "File › Save All": ["menu save all"],
        "File › Revert to Saved": ["menu revert cancel", "menu revert", "menu new buffer"],
        "File › Close Editor": ["menu close editor", "menu close editor saves", "menu settings close", "menu shortcuts close"],
        "File › Close All": ["menu close all"],
        "File › Close Others": ["menu close others"],
        "File › Reindex": ["menu reindex"],
        "Edit › Undo": ["menu undo"],
        "Edit › Redo": ["menu redo"],
        "Edit › Cut": ["menu cut line"],
        "Edit › Copy": ["menu copy"],
        "Edit › Paste": ["menu paste"],
        "Edit › Delete": ["menu delete"],
        "Edit › Select All": ["menu select all"],
        "Edit › Duplicate Line": ["menu duplicate line"],
        "Edit › Delete Line": ["menu delete line"],
        "Edit › Join Lines": ["menu join lines"],
        "Edit › Move Line Up": ["menu move line up"],
        "Edit › Move Line Down": ["menu move line down"],
        "Edit › Move Statement Up": ["menu move statement up"],
        "Edit › Move Statement Down": ["menu move statement down"],
        "Edit › Start New Line": ["menu start new line"],
        "Edit › Start New Line Before": ["menu start new line before"],
        "Edit › Toggle Case": ["menu toggle case"],
        "Edit › Sort Lines": ["menu sort lines"],
        "Edit › Select Line": ["menu select line"],
        "Edit › Select Word": ["menu select word"],
        "Edit › Extend Selection": ["menu extend selection"],
        "Edit › Shrink Selection": ["menu shrink selection"],
        "Edit › Copy Reference": ["menu copy reference"],
        "Edit › Find…": ["menu find", "menu find close"],
        "Edit › Find and Replace…": ["menu find and replace", "menu find and replace close"],
        "Edit › Find Next": ["menu find next"],
        "Edit › Find Previous": ["menu find previous"],
        "Edit › Use Selection for Find": ["menu use selection for find"],
        "Edit › Find in Project…": ["menu find in project", "menu find in project refocus", "menu find in project close"],
        "Edit › Replace in Project…": ["menu replace in project"],
    ].merging(viewNavigateClaims) { $0 + $1 }

    static let viewNavigateClaims: [String: [String]] = [
        "View › Project Sidebar": ["menu sidebar toggle", "menu sidebar restore"],
        "View › Outline": ["menu outline toggle", "menu outline restore"],
        "View › Problems": ["menu problems toggle", "menu problems restore"],
        "View › Run Output": ["menu run output toggle", "menu run output restore"],
        "View › Tests": ["menu tests toggle", "menu tests restore"],
        "View › Usages": ["menu usages toggle", "menu usages restore"],
        "View › AI": ["menu ai toggle", "menu ai restore"],
        "View › Terminal": ["menu terminal toggle", "menu terminal restore"],
        "View › Toggle Markdown Preview": ["menu markdown preview", "menu markdown preview close"],
        "View › Zoom In": ["menu zoom in"],
        "View › Zoom Out": ["menu zoom out"],
        "View › Actual Size": ["menu actual size"],
        "View › Line Numbers": ["menu line numbers toggle", "menu line numbers restore"],
        "View › Soft Wrap": ["menu soft wrap toggle", "menu soft wrap restore"],
        "View › Show Whitespace": ["menu show whitespace toggle", "menu show whitespace restore"],
        "View › Indent Guides": ["menu indent guides toggle", "menu indent guides restore"],
        "View › Code Vision": ["menu code vision toggle", "menu code vision restore"],
        "View › Open in Split": ["menu open in split"],
        "View › Toggle Split": ["menu toggle split"],
        "View › Close Split": ["menu close split", "menu open in split close"],
        "Navigate › Open Quickly…": ["menu open quickly", "menu open quickly replaces overlay", "menu open quickly close"],
        "Navigate › Recent Files…": ["menu recent files"],
        "Navigate › Back": ["menu back"],
        "Navigate › Forward": ["menu forward"],
        "Navigate › Last Edit Location": ["menu last edit"],
        "Navigate › Go to Line…": ["menu go to line", "menu go to line reopen", "menu go to line toggle"],
        "Navigate › Go to Symbol in File…": ["menu symbol in file", "menu symbol in file reopen", "menu symbol in file toggle"],
        "Navigate › Go to Symbol in Project…": ["menu symbol in project"],
        "Navigate › Go to Definition": ["menu go to definition"],
        "Navigate › Switch Header / Source": ["header source switch"],
        "Navigate › Find Usages": ["menu find usages"],
        "Navigate › Call Hierarchy": ["menu call hierarchy"],
        "Navigate › Type Hierarchy": ["menu type hierarchy"],
        "Navigate › Rename…": ["menu rename", "menu rename again", "menu rename escape open", "menu rename notice"],
        "Navigate › Safe Delete…": ["menu safe delete"],
        "Navigate › Next Problem": ["menu next problem"],
        "Navigate › Previous Problem": ["menu previous problem"],
        "Navigate › Next Method": ["menu next method"],
        "Navigate › Previous Method": ["menu previous method"],
        "Navigate › Matching Brace": ["menu matching brace"],
    ]

    static let fileEditExempt: [String: String] = [
        "Ride › Hide Others": "system item; hides every other app on the desktop",
        "Ride › Show All": "system item; unhides every other app on the desktop",
        "Edit › Start Dictation…": "system text service",
        "Edit › Emoji & Symbols": "system character palette",
        "Window › Minimize": "system window item",
        "Window › Zoom": "system window item",
        "Window › Bring All to Front": "system window item",
        "Window › Ride": "system window list entry",
        "Window › AI": "system window list entry for the AI panel window",
    ].merging(systemTextServices) { first, _ in first }

    private static let systemTextServices: [String: String] = Dictionary(
        uniqueKeysWithValues: [
            "Edit › Writing Tools › Show Writing Tools",
            "Edit › Writing Tools › Proofread",
            "Edit › Writing Tools › Rewrite",
            "Edit › Writing Tools › Make Friendly",
            "Edit › Writing Tools › Make Professional",
            "Edit › Writing Tools › Make Concise",
            "Edit › Writing Tools › Summarize",
            "Edit › Writing Tools › Create Key Points",
            "Edit › Writing Tools › Make List",
            "Edit › Writing Tools › Make Table",
            "Edit › Writing Tools › Compose…",
            "Edit › AutoFill › Contact…",
            "Edit › AutoFill › Passwords…",
            "Edit › AutoFill › Credit Card…",
        ].map { ($0, "system text service") }
    )
}
