mod home;
mod locate;
mod metadata;
mod metadata_json;
pub(crate) mod metadata_targets;
mod model;
mod name_version;
mod registry;
mod run;
mod scopes;
mod setup;
mod sysroot;
pub mod system_includes;
mod tools;

pub use home::cargo_home;
pub use locate::cargo_workspace_root;
pub use metadata::workspace_info;
pub use model::{DiscoveredCrate, Discovery};
pub use run::discover;
pub use sysroot::{rust_src_available, rustc_sysroot, sysroot_path};
pub use system_includes::{SystemIncludes, probe_args};
pub use tools::tool_status;
