mod c_outline;
mod capture;
mod edit;
mod errors;
mod fences;
mod grammar;
mod header;
mod locals;
mod markdown;
mod paint;
mod ranges;
mod rust_outline;
mod session;
mod spans;
mod symbol;
mod syntax;
mod tree_syntax;

pub use session::BufferSession;
pub use spans::source_highlights;
pub use syntax::Lang;
