use super::super::load::Files;

pub const FILES: Files = &[
    (
        "functions",
        include_str!("../../../cheatsheets/cpp/functions.toml"),
    ),
    ("items", include_str!("../../../cheatsheets/cpp/items.toml")),
    (
        "classes",
        include_str!("../../../cheatsheets/cpp/classes.toml"),
    ),
    (
        "members",
        include_str!("../../../cheatsheets/cpp/members.toml"),
    ),
    (
        "special-members",
        include_str!("../../../cheatsheets/cpp/special-members.toml"),
    ),
    (
        "operators",
        include_str!("../../../cheatsheets/cpp/operators.toml"),
    ),
    (
        "control-flow",
        include_str!("../../../cheatsheets/cpp/control-flow.toml"),
    ),
    ("loops", include_str!("../../../cheatsheets/cpp/loops.toml")),
    (
        "declarations",
        include_str!("../../../cheatsheets/cpp/declarations.toml"),
    ),
    ("types", include_str!("../../../cheatsheets/cpp/types.toml")),
    (
        "templates",
        include_str!("../../../cheatsheets/cpp/templates.toml"),
    ),
    (
        "concepts",
        include_str!("../../../cheatsheets/cpp/concepts.toml"),
    ),
    (
        "containers",
        include_str!("../../../cheatsheets/cpp/containers.toml"),
    ),
    (
        "container-ops",
        include_str!("../../../cheatsheets/cpp/container-ops.toml"),
    ),
    (
        "map-ops",
        include_str!("../../../cheatsheets/cpp/map-ops.toml"),
    ),
    (
        "algorithms",
        include_str!("../../../cheatsheets/cpp/algorithms.toml"),
    ),
    (
        "modifying-algorithms",
        include_str!("../../../cheatsheets/cpp/modifying-algorithms.toml"),
    ),
    (
        "ranges",
        include_str!("../../../cheatsheets/cpp/ranges.toml"),
    ),
    (
        "smart-pointers",
        include_str!("../../../cheatsheets/cpp/smart-pointers.toml"),
    ),
    (
        "lambdas",
        include_str!("../../../cheatsheets/cpp/lambdas.toml"),
    ),
    (
        "strings",
        include_str!("../../../cheatsheets/cpp/strings.toml"),
    ),
    (
        "streams",
        include_str!("../../../cheatsheets/cpp/streams.toml"),
    ),
    (
        "exceptions",
        include_str!("../../../cheatsheets/cpp/exceptions.toml"),
    ),
    (
        "preprocessor",
        include_str!("../../../cheatsheets/cpp/preprocessor.toml"),
    ),
    (
        "macros",
        include_str!("../../../cheatsheets/cpp/macros.toml"),
    ),
    (
        "modules",
        include_str!("../../../cheatsheets/cpp/modules.toml"),
    ),
    (
        "threads",
        include_str!("../../../cheatsheets/cpp/threads.toml"),
    ),
    ("sync", include_str!("../../../cheatsheets/cpp/sync.toml")),
    (
        "casts-literals",
        include_str!("../../../cheatsheets/cpp/casts-literals.toml"),
    ),
    (
        "expressions",
        include_str!("../../../cheatsheets/cpp/expressions.toml"),
    ),
];
