use super::super::load::Files;

pub const FILES: Files = &[
    (
        "rules",
        include_str!("../../../cheatsheets/make/rules.toml"),
    ),
    (
        "skeletons",
        include_str!("../../../cheatsheets/make/skeletons.toml"),
    ),
    (
        "variables",
        include_str!("../../../cheatsheets/make/variables.toml"),
    ),
    (
        "variables-builtin",
        include_str!("../../../cheatsheets/make/variables-builtin.toml"),
    ),
    (
        "automatic-variables",
        include_str!("../../../cheatsheets/make/automatic-variables.toml"),
    ),
    (
        "functions-text",
        include_str!("../../../cheatsheets/make/functions-text.toml"),
    ),
    (
        "functions-files",
        include_str!("../../../cheatsheets/make/functions-files.toml"),
    ),
    (
        "functions-control",
        include_str!("../../../cheatsheets/make/functions-control.toml"),
    ),
    (
        "idioms",
        include_str!("../../../cheatsheets/make/idioms.toml"),
    ),
    (
        "conditionals",
        include_str!("../../../cheatsheets/make/conditionals.toml"),
    ),
    (
        "directives",
        include_str!("../../../cheatsheets/make/directives.toml"),
    ),
    (
        "recipes",
        include_str!("../../../cheatsheets/make/recipes.toml"),
    ),
    (
        "special-targets",
        include_str!("../../../cheatsheets/make/special-targets.toml"),
    ),
    (
        "pattern-rules",
        include_str!("../../../cheatsheets/make/pattern-rules.toml"),
    ),
];
