use super::super::load::Files;

pub const FILES: Files = &[
    (
        "functions",
        include_str!("../../../cheatsheets/rust/functions.toml"),
    ),
    (
        "items",
        include_str!("../../../cheatsheets/rust/items.toml"),
    ),
    (
        "control-flow",
        include_str!("../../../cheatsheets/rust/control-flow.toml"),
    ),
    (
        "patterns",
        include_str!("../../../cheatsheets/rust/patterns.toml"),
    ),
    (
        "types",
        include_str!("../../../cheatsheets/rust/types.toml"),
    ),
    (
        "types-abstract",
        include_str!("../../../cheatsheets/rust/types-abstract.toml"),
    ),
    (
        "traits",
        include_str!("../../../cheatsheets/rust/traits.toml"),
    ),
    (
        "trait-impls",
        include_str!("../../../cheatsheets/rust/trait-impls.toml"),
    ),
    (
        "trait-impls-ops",
        include_str!("../../../cheatsheets/rust/trait-impls-ops.toml"),
    ),
    (
        "closures",
        include_str!("../../../cheatsheets/rust/closures.toml"),
    ),
    (
        "iterators",
        include_str!("../../../cheatsheets/rust/iterators.toml"),
    ),
    (
        "iterators-consume",
        include_str!("../../../cheatsheets/rust/iterators-consume.toml"),
    ),
    (
        "errors",
        include_str!("../../../cheatsheets/rust/errors.toml"),
    ),
    (
        "ownership",
        include_str!("../../../cheatsheets/rust/ownership.toml"),
    ),
    (
        "strings",
        include_str!("../../../cheatsheets/rust/strings.toml"),
    ),
    (
        "collections-vec",
        include_str!("../../../cheatsheets/rust/collections-vec.toml"),
    ),
    (
        "collections-maps",
        include_str!("../../../cheatsheets/rust/collections-maps.toml"),
    ),
    (
        "modules",
        include_str!("../../../cheatsheets/rust/modules.toml"),
    ),
    (
        "attributes",
        include_str!("../../../cheatsheets/rust/attributes.toml"),
    ),
    (
        "macros",
        include_str!("../../../cheatsheets/rust/macros.toml"),
    ),
    (
        "format-spec",
        include_str!("../../../cheatsheets/rust/format-spec.toml"),
    ),
    (
        "concurrency",
        include_str!("../../../cheatsheets/rust/concurrency.toml"),
    ),
    (
        "async",
        include_str!("../../../cheatsheets/rust/async.toml"),
    ),
    (
        "unsafe-ffi",
        include_str!("../../../cheatsheets/rust/unsafe-ffi.toml"),
    ),
    (
        "tests-docs",
        include_str!("../../../cheatsheets/rust/tests-docs.toml"),
    ),
    ("io", include_str!("../../../cheatsheets/rust/io.toml")),
    (
        "process-time",
        include_str!("../../../cheatsheets/rust/process-time.toml"),
    ),
    (
        "expressions",
        include_str!("../../../cheatsheets/rust/expressions.toml"),
    ),
    (
        "literals",
        include_str!("../../../cheatsheets/rust/literals.toml"),
    ),
    (
        "operators",
        include_str!("../../../cheatsheets/rust/operators.toml"),
    ),
];
